project_id = "ijznxjojltiutidvudes"

[functions.send-whatsapp]
verify_jwt = false

[functions.create-backup]
verify_jwt = false

[functions.restore-backup]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.mercadopago-create-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.send-chat-message]
verify_jwt = false